; ============================================================
; PlatformIO — HestiaSDK
; Deux environnements : DevKit V1 + ESP32-C3
; ============================================================

; ----------- SECTION COMMUNE  ---------------------------------
[env]
framework = arduino

lib_ldf_mode = deep+
; IMPORTANT:
; Ne pas référencer ce projet lui-même comme librairie externe, sinon `src/`
; est compilé 2 fois (objets dupliqués au link).
; lib_extra_dirs =
;     ../HestiaSDK

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -Iinclude
    -I../HestiaSDK/src

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.0
    256dpi/MQTT @ ^2.5.0
    https://github.com/Hestia-system/Hestia-tempo.git
; extra_config = platformio.ini

; ----------- ENV 1 : ESP32 DevKit V1 ---------------------------
; UART0 → Serial → USB CH340
[env:devkit]
platform = https://github.com/platformio/platform-espressif32.git#v6.10.0
board = esp32doit-devkit-v1
build_flags =
    ${env.build_flags}
    ; IMPORTANT : NE PAS activer USB CDC ici (pas supporté)

; ----------- ENV 2 : ESP32-C3 ----------------------------------
; USB natif → Serial sur USB
[env:c3]
platform = https://github.com/platformio/platform-espressif32.git#v6.10.0
board = esp32-c3-devkitm-1
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; ----------- ENV 3 : XIAO ESP32-C6 Mini ------------------------
; USB natif → Serial sur USB
[env:xiao_c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6

lib_deps =
    ${env.lib_deps}
    https://github.com/junkfix/dhtESP32-rmt.git
    https://github.com/pstolarz/OneWireNg.git
    adafruit/Adafruit ADS1X15 @ ^2.5.0
lib_ignore =
    OneWire
    DallasTemperature
build_flags =
    ${env.build_flags}
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; ----------- ENV 4 : ESP32-S3 ----------------------------------
[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.37
board = esp32-s3-devkitc-1
framework = arduino
build_flags =
    ${env.build_flags}
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
lib_deps =
    ${env.lib_deps}
