/**
 * ============================================================================
 * DeviceParams.h — Static JSON Schema for Device-Level Parameters
 * ============================================================================
 *
 * This file belongs exclusively to the DEVICE layer (Virgo, Ji_Piscin, etc.).
 * It provides HestiaConfig with the JSON definition describing all
 * non-provisioning firmware parameters. The HestiaSDK library remains neutral
 * and independent from these values.
 *
 * The JSON schema is loaded at boot through:
 *      HestiaConfig::loadDeviceParams(HESTIA_PARAM_JSON);
 *
 * IMPORTANT:
 *  - Only firmware-driven (non-provisioning) parameters are defined here.
 *  - Provisioning parameters (WiFi, MQTT, etc.) will be migrated later.
 *  - This file will eventually be auto-generated by the future Hestia Generator.
 *
 * ============================================================================
 */


#pragma once
#include <pgmspace.h>



static const char HESTIA_PARAM_JSON[] PROGMEM = R"json(
{
  "version": 2,
  "params": [
    {
      "key": "model",
      "type": "string",
      "label": "Device Model",
      "provisioning": false,
      "required": true,
      "critical": true,
      "default": "HESTIA_SDK",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 32 }
    },
    {
      "key": "version_prog",
      "type": "string",
      "label": "Firmware Version",
      "provisioning": false,
      "required": true,
      "critical": true,
      "default": "V1.1.2",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 16 }
    },
    {
      "key": "iot_alive_ms",
      "type": "number",
      "label": "IoT Alive Interval (ms)",
      "provisioning": false,
      "required": true,
      "critical": true,
      "default": "5000",
      "decimals": 0,
      "validate": { "min": 100, "max": 60000 }
    },
    {
      "key": "watchdog_ms",
      "type": "number",
      "label": "Watchdog Timeout (ms)",
      "provisioning": false,
      "required": true,
      "critical": true,
      "default": "20000",
      "decimals": 0,
      "validate": { "min": 1000, "max": 120000 }
    },
    {
      "key": "mqtt_flush_window",
      "type": "number",
      "label": "MQTT Flush Window (ms)",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "500",
      "decimals": 0,
      "validate": { "min": 10, "max": 10000 }
    },
    {
      "key": "ha_heartbeat_timeout_ms",
      "type": "number",
      "label": "HA Heartbeat Timeout (ms)",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "16000",
      "decimals": 0,
      "validate": { "min": 5000, "max": 300000 }
    },
    {
      "key": "device_id",
      "type": "string",
      "label": "Device Identifier",
      "provisioning": false,
      "required": true,
      "critical": true,
      "default": "Virgo",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 32 }
    },
    {
      "key": "ha_log_topic",
      "type": "string",
      "label": "Home Assistant Log Topic",
      "provisioning": false,
      "required": true,
      "critical": true,
      "default": "Virgo/log/toHA",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 128 }
    },
    {
      "key": "led_onboard",
      "type": "number",
      "label": "Onboard LED Pin",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "8",
      "decimals": 0,
      "validate": { "min": -1, "max": 48 }
    },
    {
      "key": "pin_provisioning",
      "type": "number",
      "label": "Provisioning Button Pin",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "9",
      "decimals": 0,
      "validate": { "min": -1, "max": 48 }
    },
    {
      "key": "prov_hold_ms",
      "type": "number",
      "label": "Provisioning Hold Duration (ms)",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "5000",
      "decimals": 0,
      "validate": { "min": 1000, "max": 60000 }
    },
    {
      "key": "wifi_ssid",
      "type": "string",
      "label": "WiFi SSID",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 32 }
    },
    {
      "key": "wifi_pass",
      "type": "string",
      "label": "WiFi Password",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 64 }
    },
    {
      "key": "mqtt_ip",
      "type": "string",
      "label": "MQMQTT Broker IP",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "ip"
    },
    {
      "key": "mqtt_port",
      "type": "int",
      "label": "MQTT Port",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "1883",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "min": 1, "max": 65535 }
    },
    {
      "key": "mqtt_user",
      "type": "string",
      "label": "MQTT Username",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 64 }
    },
    {
      "key": "mqtt_pass",
      "type": "string",
      "label": "MQTT Password",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 64 }
    },
    {
      "key": "timezone",
      "type": "string",
      "label": "Timezone",
      "provisioning": true,
      "required": true,
      "critical": false,
      "default": "America/Toronto",
      "pattern": "anything",
      "options": [
        "Pacific/Midway",
        "Pacific/Honolulu",
        "America/Anchorage",
        "America/Los_Angeles",
        "America/Denver",
        "America/Chicago",
        "America/Toronto",
        "America/Santiago",
        "America/Sao_Paulo",
        "Atlantic/South_Georgia",
        "Atlantic/Azores",
        "Europe/London",
        "Europe/Paris",
        "Europe/Athens",
        "Europe/Moscow",
        "Asia/Dubai",
        "Asia/Karachi",
        "Asia/Dhaka",
        "Asia/Bangkok",
        "Asia/Hong_Kong",
        "Asia/Tokyo",
        "Australia/Sydney",
        "Pacific/Noumea",
        "Pacific/Auckland"
      ]
    },
    {
      "key": "iot_user",
      "type": "string",
      "label": "IoT Username",
      "provisioning": true,
      "required": false,
      "critical": false,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 0, "maxLen": 64 }
    },
    {
      "key": "iot_pass",
      "type": "string",
      "label": "IoT Password",
      "provisioning": true,
      "required": false,
      "critical": false,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 0, "maxLen": 64 }
    }

  ]
}
)json";


// ============================================================================
// Aliases for device parameters (auto-linked to HestiaConfig)
// ============================================================================
#define PARAM_MODEL              (HestiaConfig::getParamObj("model"))
#define PARAM_VERSION_PROG       (HestiaConfig::getParamObj("version_prog"))
#define PARAM_IOT_ALIVE_MS       (HestiaConfig::getParamObj("iot_alive_ms"))
#define PARAM_WATCHDOG_MS        (HestiaConfig::getParamObj("watchdog_ms"))
#define PARAM_MQTT_FLUSH_WINDOW  (HestiaConfig::getParamObj("mqtt_flush_window"))
#define PARAM_DEVICE_ID          (HestiaConfig::getParamObj("device_id"))
#define PARAM_HA_LOG_TOPIC       (HestiaConfig::getParamObj("ha_log_topic"))
#define PARAM_LED_ONBOARD        (HestiaConfig::getParamObj("led_onboard"))
#define PARAM_PIN_PROV           (HestiaConfig::getParamObj("pin_provisioning"))
#define PARAM_PROV_HOLD_MS       (HestiaConfig::getParamObj("prov_hold_ms"))