/**
 * ============================================================================
 * DeviceParams.h — Static JSON Schema for Device-Level Parameters
 * ============================================================================
 *
 * This file belongs exclusively to the DEVICE layer (Virgo, Ji_Piscin, etc.).
 * It provides HestiaConfig with the JSON definition describing all
 * non-provisioning firmware parameters. The HestiaSDK library remains neutral
 * and independent from these values.
 *
 * The JSON schema is loaded at boot through:
 *      HestiaConfig::loadDeviceParams(HESTIA_PARAM_JSON);
 *
 * IMPORTANT:
 *  - Only firmware-driven (non-provisioning) parameters are defined here.
 *  - Provisioning parameters (WiFi, MQTT, etc.) will be migrated later.
 *  - This file will eventually be auto-generated by the future Hestia Generator.
 *

 * ============================================================================
 * DeviceParams JSON — Schema Reference
 * ============================================================================
 *
 * Each entry in the "params" array defines a single device parameter managed
 * by HestiaConfig and optionally exposed through the provisioning system.
 *
 * --------------------------------------------------------------------------
 * Core fields (mandatory unless stated otherwise)
 * --------------------------------------------------------------------------
 *
 * key (string)
 *   Unique identifier of the parameter.
 *   Used as:
 *     - internal lookup key (HestiaConfig::getParamObj)
 *     - NVS storage key (may be shortened internally)
 *
 * type (string)
 *   Logical data type of the parameter.
 *   Supported values:
 *     - "string"
 *     - "number"   (integer or float, formatted via decimals)
 *     - "int"      (legacy alias, treated as number)
 *     - "bool"
 *
 * label (string, optional)
 *   Human-readable label displayed in the provisioning UI.
 *   If omitted, defaults to the value of "key".
 *
 * default (string)
 *   Default value used when:
 *     - the parameter is not present in NVS
 *     - lazy initialization is enabled
 *
 * --------------------------------------------------------------------------
 * Provisioning & lifecycle control
 * --------------------------------------------------------------------------
 *
 * provisioning (bool)
 *   Indicates whether the parameter is user-configurable via provisioning.
 *
 *   - false → firmware / device-level parameter
 *              (not shown in provisioning UI)
 *   - true  → user-configurable parameter
 *
 * required (bool)
 *   Indicates whether a non-empty value is required for configuration validity.
 *
 *   - If true and value is empty → configuration is invalid
 *   - Used by:
 *       - validation logic
 *       - HTML "required" attribute in provisioning UI
 *
 * critical (bool)
 *   Indicates whether an invalid value prevents normal device operation.
 *
 *   Intended semantics:
 *     - true  → invalid value may force provisioning mode
 *     - false → invalid value may be tolerated
 *
 *   Note:
 *     This flag is conceptually defined but not yet fully enforced
 *     by the validation pipeline.
 *
 * --------------------------------------------------------------------------
 * Formatting & normalization
 * --------------------------------------------------------------------------
 *
 * decimals (int, optional)
 *   Number of decimal places used when formatting numeric values.
 *
 *   - 0 → integer formatting
 *   - >0 → fixed-point formatting ex "0.1" "0.01", etc
 *
 * pattern (string, optional)
 *   Semantic validation pattern applied to string values.
 *   Supported values:
 *     - "anything"  (default)
 *     - "ip"        (IPv4 address)
 *     - "hostname"
 *     - "bool"
 *
 * --------------------------------------------------------------------------
 * Validation rules (optional)
 * --------------------------------------------------------------------------
 *
 * validate (object)
 *   Optional validation constraints applied to the value.
 *
 *   Supported keys:
 *     - minLen (int)  : minimum string length
 *     - maxLen (int)  : maximum string length
 *     - min    (num)  : minimum numeric value
 *     - max    (num)  : maximum numeric value
 *
 *   Validation is applied during:
 *     - provisioning
 *     - configuration validation (validateR2)
 *
 * --------------------------------------------------------------------------
 * UI helpers (optional)
 * --------------------------------------------------------------------------
 *
 * options (array of strings)
 *   Defines a fixed set of allowed values.
 *   When present:
 *     - rendered as <select> in provisioning UI
 *     - value must match one of the options
 *
 * --------------------------------------------------------------------------
 * Source of truth
 * --------------------------------------------------------------------------
 *
 * The JSON schema is the single authoritative definition of:
 *   - parameter existence
 *   - default values
 *   - validation rules
 *
 * Parameters not present in this schema will never be instantiated,
 * loaded from NVS, or exposed by the system.
 *
 * ============================================================================
 */



#pragma once
#include <pgmspace.h>



static const char HESTIA_PARAM_JSON[] PROGMEM = R"json(
{
  "version": 2,
  "params": [
    {
      "key": "model",
      "type": "string",
      "label": "Device Model",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "HESTIA_SDK",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 32 }
    },
    {
      "key": "version_prog",
      "type": "string",
      "label": "Firmware Version",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "V1.1.6",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 16 }
    },
    {
      "key": "iot_alive_ms",
      "type": "number",
      "label": "IoT Alive Interval (ms)",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "5000",
      "decimals": 0,
      "validate": { "min": 100, "max": 60000 }
    },
    {
      "key": "watchdog_ms",
      "type": "number",
      "label": "Watchdog Timeout (ms)",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "20000",
      "decimals": 0,
      "validate": { "min": 1000, "max": 120000 }
    },
    {
      "key": "mqtt_flush_window",
      "type": "number",
      "label": "MQTT Flush Window (ms)",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "500",
      "decimals": 0,
      "validate": { "min": 10, "max": 10000 }
    },
    {
      "key": "ha_heartbeat_timeout_ms",
      "type": "number",
      "label": "HA Heartbeat Timeout (ms)",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "16000",
      "decimals": 0,
      "validate": { "min": 5000, "max": 300000 }
    },
    {
      "key": "device_id",
      "type": "string",
      "label": "Device Identifier",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "Virgo",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 32 }
    },
    {
      "key": "ha_log_topic",
      "type": "string",
      "label": "Home Assistant Log Topic",
      "provisioning": false,
      "required": true,
      "critical": false,
      "default": "Virgo/log/toHA",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 128 }
    },
    {
      "key": "wifi_ssid",
      "type": "string",
      "label": "WiFi SSID",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 32 }
    },
    {
      "key": "wifi_pass",
      "type": "string",
      "label": "WiFi Password",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 64 }
    },
    {
      "key": "mqtt_ip",
      "type": "string",
      "label": "MQMQTT Broker IP",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "ip"
    },
    {
      "key": "mqtt_port",
      "type": "int",
      "label": "MQTT Port",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "1883",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "min": 1, "max": 65535 }
    },
    {
      "key": "mqtt_user",
      "type": "string",
      "label": "MQTT Username",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 64 }
    },
    {
      "key": "mqtt_pass",
      "type": "string",
      "label": "MQTT Password",
      "provisioning": true,
      "required": true,
      "critical": true,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 1, "maxLen": 64 }
    },
    {
      "key": "timezone",
      "type": "string",
      "label": "Timezone",
      "provisioning": true,
      "required": true,
      "critical": false,
      "default": "America/Toronto",
      "pattern": "anything",
      "options": [
        "Pacific/Midway",
        "Pacific/Honolulu",
        "America/Anchorage",
        "America/Los_Angeles",
        "America/Denver",
        "America/Chicago",
        "America/Toronto",
        "America/Santiago",
        "America/Sao_Paulo",
        "Atlantic/South_Georgia",
        "Atlantic/Azores",
        "Europe/London",
        "Europe/Paris",
        "Europe/Athens",
        "Europe/Moscow",
        "Asia/Dubai",
        "Asia/Karachi",
        "Asia/Dhaka",
        "Asia/Bangkok",
        "Asia/Hong_Kong",
        "Asia/Tokyo",
        "Australia/Sydney",
        "Pacific/Noumea",
        "Pacific/Auckland"
      ]
    },
    {
      "key": "iot_user",
      "type": "string",
      "label": "IoT Username",
      "provisioning": true,
      "required": false,
      "critical": false,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 0, "maxLen": 64 }
    },
    {
      "key": "iot_pass",
      "type": "string",
      "label": "IoT Password",
      "provisioning": true,
      "required": false,
      "critical": false,
      "default": "",
      "decimals": 0,
      "pattern": "anything",
      "validate": { "minLen": 0, "maxLen": 64 }
    }

  ]
}
)json";


// ============================================================================
// Aliases for device parameters (auto-linked to HestiaConfig)
// ============================================================================
#define PARAM_MODEL              (HestiaConfig::getParamObj("model"))
#define PARAM_VERSION_PROG       (HestiaConfig::getParamObj("version_prog"))
#define PARAM_IOT_ALIVE_MS       (HestiaConfig::getParamObj("iot_alive_ms"))
#define PARAM_WATCHDOG_MS        (HestiaConfig::getParamObj("watchdog_ms"))
#define PARAM_MQTT_FLUSH_WINDOW  (HestiaConfig::getParamObj("mqtt_flush_window"))
#define PARAM_DEVICE_ID          (HestiaConfig::getParamObj("device_id"))
#define PARAM_HA_LOG_TOPIC       (HestiaConfig::getParamObj("ha_log_topic"))
